# Generated by Django 6.0 on 2025-12-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='source_code',
            field=models.FileField(blank=True, null=True, upload_to='projects/code/'),
        ),
    ]
