# Generated by Django 6.0 on 2025-12-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_source_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, help_text='Optional: Link to GitHub repository', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor_name',
            field=models.CharField(blank=True, help_text='Name of your supervisor', max_length=100),
        ),
    ]
